# Dev Settings
DEBUG = True
HOST = '0.0.0.0'
PORT = 5000
WTF_CSRF_ENABLED = True
SECRET_KEY = ''

DB_HOST = ''
DB_NAME = ''
DB_USER = ''
DB_PASS = ''

#EMAIL SETTINGS
MAIL_SERVER='smtp.gmail.com',
MAIL_PORT=465,
MAIL_USE_SSL=True,
MAIL_USERNAME = 'you@google.com',
MAIL_PASSWORD = 'GooglePasswordHere'

ADMIN_EMAIL = ''
ADMIN_USERNAME = ''
ADMIN_PASSWORD = ''

SECURITY_CONFIRMABLE = False
SECURITY_TRACKABLE = True
LOGIN_DISABLED = False
SECURITY_PASSWORD_HASH = 'pbkdf2_sha512'
SECURITY_PASSWORD_SALT = 'password_salt'

SQLALCHEMY_DATABASE_URI = ''
SQLALCHEMY_TRACK_MODIFICATIONS = False